name: Test

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 0 * * *"

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch data from ARSOXMLWrapper API
        run: python fetch_data.py https://arsoxmlwrapper.app.grega.xyz/api/air/archive data/raw/air/



  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest